sonar.projectKey=Rakeshu99_Recipe-webapp-service
sonar.projectName=Recipe Webapp Backend Service
sonar.projectVersion=1.0
sonar.organization=rakeshu99

sonar.sources=src/main/java
sonar.tests=src/test/java
sonar.java.binaries=target/classes

sonar.language=java
sonar.sourceEncoding=UTF-8
