sonar.projectKey=adithyan-ie_Recipe-webapp-service
sonar.organization=adithyan-ie
sonar.host.url=https://sonarcloud.io

sonar.sources=src
sonar.java.binaries=target/classes
sonar.branch=main
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml