name: Dev - Test, Build & Deploy (Container)

on:
  push:
    branches: [ main ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:

  code-analysis:
    runs-on: ubuntu-latest
    steps:
      # 1️⃣ Checkout code
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # required for Sonar blame info

      # 2️⃣ Set up JDK 17
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
        id: java

      # 3️⃣ Cache Maven dependencies
      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Cache SonarQube packages
        uses: actions/cache@v4
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      # 7️⃣ SonarCloud scan
      - name: SonarCloud Scan
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          mvn -B clean verify sonar:sonar \
            -Dsonar.projectKey=adithyan-ie_Recipe-webapp-service \
            -Dsonar.organization=adithyan-ie \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml \
            -Dsonar.java.binaries=target/classes \
            -Dsonar.sources=src/main/java \
            -Dsonar.projectName="Recipe-webapp-service"

      - name: Build project
        run: mvn -B clean install -DskipTests

      - name: Run OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        with:
          project: "recipe-backend"
          path: "."
          format: "HTML"
          out: "dependency-check-report"
        env:
          JAVA_HOME: /opt/jdk

      - name: Upload depedency analysis Report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: dependency-check-report

  run-test:
    needs: code-analysis
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    steps:
      - uses: actions/checkout@v4

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Run unit tests
        run: mvn clean test

      - name: Run verify
        run: mvn verify -DskipTests

      - name: Upload JUnit Reports
        uses: actions/upload-artifact@v4
        with:
          name: junit-reports
          path: target/surefire-reports/*.xml

  build:
    needs: run-test
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package -DskipTests=true