# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Scan, Run Unit and BDD Test and Build App

on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_run:
    workflows: ["terraform Infra"]   # must match the workflow name in terraform.yml
    types:
      - completed

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package -DskipTests=true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: recipe-webapp-service
          path: '${{ github.workspace }}/target/*.jar'

  
  docker-build-push:
    needs: run-test
    runs-on: ubuntu-latest
    if: ${{ github.event_name != 'workflow_run' || github.event.workflow_run.conclusion == 'success' }}

    permissions:
      contents: read
      packages: write
      id-token: write

    outputs:
      image: ${{ steps.image.outputs.image }}

    steps:
      - uses: actions/checkout@v4

      - name: Set image tag
        id: image
        run: |
          IMAGE=${{ secrets.ACR_LOGIN_SERVER }}/recipe-backend-prod:${{ github.sha }}
          echo "image=$IMAGE" >> $GITHUB_OUTPUT

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build & Push
        run: |
          docker build -t ${{ steps.image.outputs.image }} .
          docker push ${{ steps.image.outputs.image }}

  deploy-prod:
    needs: docker-build-push
    runs-on: ubuntu-latest

    environment:
     name: production

    permissions:
        id-token: write
        contents: read

    steps:

      - uses: actions/checkout@v4

      - name: Azure Login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # ─────────────────────────────────────
      # Terraform read-only (state source)
      # ─────────────────────────────────────
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init (infra state only)
        working-directory: infra
        env:
          ARM_USE_OIDC: "true"
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        run: |
          terraform init \
            -backend-config="resource_group_name=rg-tfstate" \
            -backend-config="storage_account_name=sttfstaterecipewebapp" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=recipe-webapp.tfstate"

      - name: Read use_slots from Terraform
        id: tf
        working-directory: infra
        run: |
          echo "use_slots=$(terraform output -raw use_slots)" >> $GITHUB_OUTPUT

      - name: Swap staging -> production
        if: steps.tf.outputs.use_slots == 'true'
        run: |
          az webapp deployment slot swap \
            --name ${{ secrets.AZURE_WEBAPP_NAME }} \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --slot staging \
            --target-slot production

      
  # deploy-production:
  # needs: deploy-staging
  # runs-on: ubuntu-latest

  # environment:
  #   name: production

  # permissions:
  #   id-token: write
  #   contents: read

  # steps:
  #   - name: Azure Login (OIDC)
  #     uses: azure/login@v2
  #     with:
  #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #   - name: Swap staging -> production
  #     run: |
  #       az webapp deployment slot swap \
  #         --name ${{ secrets.AZURE_WEBAPP_NAME }} \
  #         --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
  #         --slot staging \
  #         --target-slot production