# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Scan, Run Unit and BDD Test and Build App

on:
  push:
    branches: [ release ]
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache Maven
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-m2

      - name: Set up Java version
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'microsoft'

      - name: Build with Maven
        run: mvn clean package -DskipTests=true

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: recipe-webapp-service
          path: '${{ github.workspace }}/target/*.jar'

  
  docker-build-push:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write   # IMPORTANT for GHCR

    steps:
      # 1️⃣ Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2️⃣ Log in to GitHub Container Registry
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3️⃣ Set up Docker build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 4️⃣ Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/recipe-backend:${{ github.ref_name }}:${{ github.run_number }} .

      # 5️⃣ Push Docker image
      - name: Push Docker image
        run: |
          docker push ghcr.io/${{ github.repository_owner }}/recipe-backend:${{ github.ref_name }} :${{ github.run_number }}



  # deploy-staging:
  #   needs: docker-build-push
  #   runs-on: ubuntu-latest

  #   environment:
  #     name: staging

  #   steps:
  #     - name: Azure Login
  #       uses: azure/login@v2
  #       with:
  #         creds: ${{ secrets.AZURE_CREDENTIALS }}

  #     - name: Deploy container to staging slot
  #       uses: azure/webapps-deploy@v3
  #       with:
  #         app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
  #         slot-name: staging
  #         images: ${{ needs.docker-build-push.outputs.image }}

  #     - name: Restart staging
  #       run: |
  #         az webapp restart \
  #           --name ${{ secrets.AZURE_WEBAPP_NAME }} \
  #           --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
  #           --slot staging

  #     - name: Smoke test
  #       run: |
  #         curl -f https://${{ secrets.AZURE_WEBAPP_NAME }}-staging.azurewebsites.net/actuator/health

  # deploy-production:
  # needs: deploy-staging
  # runs-on: ubuntu-latest

  # environment:
  #   name: production

  # permissions:
  #   id-token: write
  #   contents: read

  # steps:
  #   - name: Azure Login (OIDC)
  #     uses: azure/login@v2
  #     with:
  #       client-id: ${{ secrets.AZURE_CLIENT_ID }}
  #       tenant-id: ${{ secrets.AZURE_TENANT_ID }}
  #       subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

  #   - name: Swap staging -> production
  #     run: |
  #       az webapp deployment slot swap \
  #         --name ${{ secrets.AZURE_WEBAPP_NAME }} \
  #         --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
  #         --slot staging \
  #         --target-slot production